/**
 * Unit tests for the theme.ts emitter: exact-name tree mirroring, the
 * light/darkTheme two-tree convention, value literal rendering, and
 * determinism. The tsc --noEmit execution harness lives in
 * emitters.e2e.test.ts (integration through the production CLI).
 */

import { describe, expect, it } from 'vitest';
import { emitThemeTs, tokenValueToTs } from '../src/build/emitters/ts.ts';
import type { EmitterContext, FlatToken } from '../src/build/compile.ts';
import type { TokensDocument } from '../src/schema/types.ts';

function flat(path: string[], type: FlatToken['type'], value: FlatToken['value']): FlatToken {
  return { path, dotPath: path.join('.'), type, value };
}

function ctx(light: FlatToken[], darkOverrides: FlatToken[] = []): EmitterContext {
  return { light, darkOverrides, lightDocument: {} as TokensDocument };
}

describe('tokenValueToTs', () => {
  it('renders strings as quoted literals and numbers bare', () => {
    expect(tokenValueToTs('#3b63a8')).toBe('"#3b63a8"');
    expect(tokenValueToTs(700)).toBe('700');
    expect(tokenValueToTs(1.55)).toBe('1.55');
  });

  it('renders arrays inline (fontFamily stacks, cubicBezier)', () => {
    expect(tokenValueToTs(['Inter', 'Segoe UI'])).toBe('["Inter", "Segoe UI"]');
    expect(tokenValueToTs([0.4, 0, 0.2, 1])).toBe('[0.4, 0, 0.2, 1]');
  });

  it('renders shadow objects with the canonical key order', () => {
    expect(
      tokenValueToTs({ color: '#0000001f', offsetX: '0px', offsetY: '2px', blur: '8px', spread: '-1px' }),
    ).toBe('{ color: "#0000001f", offsetX: "0px", offsetY: "2px", blur: "8px", spread: "-1px" }');
  });
});

describe('emitThemeTs', () => {
  const light = [
    flat(['color', 'semantic', 'bg'], 'color', '#fcfcfd'),
    flat(['color', 'semantic', 'text-muted'], 'color', '#566070'),
    flat(['space', '1'], 'dimension', '0.25rem'),
    flat(['type', 'weight', 'bold'], 'fontWeight', 700),
  ];
  const dark = [flat(['color', 'semantic', 'bg'], 'color', '#14181f')];

  it('starts with the DO-NOT-EDIT header, LF only, trailing newline', () => {
    const [file] = emitThemeTs(ctx(light, dark));
    expect(file!.relPath).toBe('theme.ts');
    expect(file!.content.startsWith('/* GENERATED by on-brand - DO NOT EDIT.')).toBe(true);
    expect(file!.content).not.toContain('\r');
    expect(file!.content.endsWith('\n')).toBe(true);
  });

  it('mirrors token paths with EXACT names: identifier keys bare, others quoted', () => {
    const [file] = emitThemeTs(ctx(light, dark));
    expect(file!.content).toContain('bg: "#fcfcfd"');
    expect(file!.content).toContain('"text-muted": "#566070"'); // hyphen -> quoted key
    expect(file!.content).toContain('"1": "0.25rem"'); // numeric name -> quoted key
    expect(file!.content).toContain('bold: 700');
  });

  it('emits BOTH trees: darkTheme overrides colors, carries light values elsewhere', () => {
    const [file] = emitThemeTs(ctx(light, dark));
    const themeAt = file!.content.indexOf('export const theme = {');
    const darkAt = file!.content.indexOf('export const darkTheme = {');
    expect(themeAt).toBeGreaterThan(-1);
    expect(darkAt).toBeGreaterThan(themeAt);
    const darkPart = file!.content.slice(darkAt);
    expect(darkPart).toContain('bg: "#14181f"'); // overridden
    expect(darkPart).toContain('"text-muted": "#566070"'); // not overridden -> light value
    expect(darkPart).toContain('bold: 700');
  });

  it('darkTheme mirrors the light tree when there is no overlay (both modes always exist)', () => {
    const [file] = emitThemeTs(ctx(light, []));
    const darkPart = file!.content.slice(file!.content.indexOf('export const darkTheme'));
    expect(darkPart).toContain('bg: "#fcfcfd"');
  });

  it('exports as-const trees and the Theme/DarkTheme types', () => {
    const [file] = emitThemeTs(ctx(light, dark));
    expect(file!.content).toContain('} as const;');
    expect(file!.content).toContain('export type Theme = typeof theme;');
    expect(file!.content).toContain('export type DarkTheme = typeof darkTheme;');
  });
});
