/**
 * Unit tests for the DESIGN.md emitter: front-matter mapping (name/description
 * sources, color/spacing/rounded key derivation, the `primary` alias, the
 * injectivity gate), complete body tables with dark columns, extension
 * sections (Motion / Dark Mode / Other Tokens), and determinism. The
 * production-path integration is the golden byte-match at the bottom of THIS
 * file (spawned init+build through bin/onbrand.mjs), matching the
 * svg/components per-emitter precedent.
 */

import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, describe, expect, it } from 'vitest';
import { emitDesignMd, tokenValueToText } from '../src/build/emitters/design-md.ts';
import { EXIT_OK } from '../src/cli.ts';
import { TokenValidationError } from '../src/schema/validate.ts';
import type { EmitterContext, FlatToken } from '../src/build/compile.ts';
import type { TokensDocument } from '../src/schema/types.ts';

function flat(
  path: string[],
  type: FlatToken['type'],
  value: FlatToken['value'],
  description?: string,
): FlatToken {
  return {
    path,
    dotPath: path.join('.'),
    type,
    value,
    ...(description !== undefined ? { description } : {}),
  };
}

function ctx(
  light: FlatToken[],
  darkOverrides: FlatToken[] = [],
  lightDocument: TokensDocument = {} as TokensDocument,
  darkDocument?: TokensDocument,
): EmitterContext {
  return {
    light,
    darkOverrides,
    lightDocument,
    ...(darkDocument !== undefined ? { darkDocument } : {}),
  };
}

/** Content of the YAML front-matter block (between the two --- fences). */
function frontMatter(content: string): string {
  const end = content.indexOf('\n---\n');
  expect(end).toBeGreaterThan(-1);
  return content.slice(0, end);
}

const light = [
  flat(['color', 'semantic', 'bg'], 'color', '#fcfcfd'),
  flat(['color', 'semantic', 'accent'], 'color', '#3b63a8'),
  flat(['color', 'primitive', 'brand', '1'], 'color', '#fbfcfe'),
  flat(['font', 'sans'], 'fontFamily', ['Inter', 'system-ui']),
  flat(['type', 'weight', 'bold'], 'fontWeight', 700),
  flat(['space', '1'], 'dimension', '0.25rem'),
  flat(['radius', 'sm'], 'dimension', '4px'),
  flat(
    ['shadow', 'elevation-1'],
    'shadow',
    { color: '#1f242c14', offsetX: '0px', offsetY: '1px', blur: '2px', spread: '0px' },
  ),
  flat(['motion', 'duration', 'fast'], 'duration', '120ms'),
  flat(['motion', 'easing', 'standard'], 'cubicBezier', [0.4, 0, 0.2, 1]),
];
const dark = [flat(['color', 'semantic', 'bg'], 'color', '#14181f')];

describe('tokenValueToText', () => {
  it('renders strings bare, numbers bare, arrays comma-joined', () => {
    expect(tokenValueToText('#3b63a8')).toBe('#3b63a8');
    expect(tokenValueToText(700)).toBe('700');
    expect(tokenValueToText(['Inter', 'Segoe UI'])).toBe('Inter, Segoe UI');
    expect(tokenValueToText([0.4, 0, 0.2, 1])).toBe('0.4, 0, 0.2, 1');
  });

  it('renders shadows in the CSS box-shadow order', () => {
    expect(
      tokenValueToText({ color: '#0000001f', offsetX: '0px', offsetY: '2px', blur: '8px', spread: '-1px' }),
    ).toBe('0px 2px 8px -1px #0000001f');
  });
});

describe('emitDesignMd', () => {
  it('emits DESIGN.md: front-matter fences, generated comment, LF-only, trailing newline, ASCII', () => {
    const [file] = emitDesignMd(ctx(light, dark));
    expect(file!.relPath).toBe('DESIGN.md');
    expect(file!.content.startsWith('---\n# GENERATED by on-brand - DO NOT EDIT.')).toBe(true);
    expect(file!.content).not.toContain('\r');
    expect(file!.content.endsWith('\n')).toBe(true);
    for (let i = 0; i < file!.content.length; i++) {
      const code = file!.content.charCodeAt(i);
      const ok = code === 10 || (code >= 32 && code <= 126);
      if (!ok) throw new Error(`non-ASCII char code ${code} at offset ${i}`);
    }
  });

  it('defaults name to "Brand" and pins the spec version literal', () => {
    const [file] = emitDesignMd(ctx(light));
    const fm = frontMatter(file!.content);
    expect(fm).toContain('name: "Brand"');
    expect(fm).toContain('version: "alpha"');
  });

  it('reads name/description from $extensions.onbrand, description falls back to root $description', () => {
    const doc = {
      $description: 'Root description.',
      $extensions: { onbrand: { schemaVersion: 1, name: 'Acme', description: 'Acme brand.' } },
    } as unknown as TokensDocument;
    const [file] = emitDesignMd(ctx(light, [], doc));
    const fm = frontMatter(file!.content);
    expect(fm).toContain('name: "Acme"');
    expect(fm).toContain('description: "Acme brand."');

    const fallbackDoc = { $description: 'Root description.' } as unknown as TokensDocument;
    const [fallbackFile] = emitDesignMd(ctx(light, [], fallbackDoc));
    expect(frontMatter(fallbackFile!.content)).toContain('description: "Root description."');
  });

  it('maps colors with the leading color group dropped and paths hyphen-joined', () => {
    const [file] = emitDesignMd(ctx(light));
    const fm = frontMatter(file!.content);
    expect(fm).toContain('  semantic-bg: "#fcfcfd"');
    expect(fm).toContain('  primitive-brand-1: "#fbfcfe"');
  });

  it('aliases primary from color.semantic.accent (first entry) and says so in the body', () => {
    const [file] = emitDesignMd(ctx(light));
    const fm = frontMatter(file!.content);
    expect(fm).toContain('colors:\n  primary: "#3b63a8"\n');
    expect(file!.content).toContain('The front-matter `primary` entry aliases `color.semantic.accent`.');
  });

  it('emits no alias when a token already derives the key primary', () => {
    const withPrimary = [...light, flat(['color', 'primary'], 'color', '#111111')];
    const [file] = emitDesignMd(ctx(withPrimary));
    const fm = frontMatter(file!.content);
    expect(fm).toContain('  primary: "#111111"');
    expect(file!.content).not.toContain('entry aliases');
  });

  it('quotes numeric-looking YAML keys so they parse as strings', () => {
    const [file] = emitDesignMd(ctx(light));
    const fm = frontMatter(file!.content);
    expect(fm).toContain('spacing:');
    expect(fm).toContain('  "1": "0.25rem"');
    expect(fm).toContain('rounded:');
    expect(fm).toContain('  sm: "4px"');
  });

  it('omits typography front matter (no composite fabrication) but tables every font token', () => {
    const [file] = emitDesignMd(ctx(light));
    expect(frontMatter(file!.content)).not.toContain('typography:');
    expect(file!.content).toContain('## Typography');
    expect(file!.content).toContain('| `font.sans` | `Inter, system-ui` |');
    expect(file!.content).toContain('| `type.weight.bold` | `700` |');
  });

  it('fails loud (naming both parties) when hyphen-joined keys collide', () => {
    const colliding = [
      flat(['color', 'semantic', 'text-muted'], 'color', '#566070'),
      flat(['color', 'semantic', 'text', 'muted'], 'color', '#000000'),
    ];
    expect(() => emitDesignMd(ctx(colliding))).toThrowError(TokenValidationError);
    expect(() => emitDesignMd(ctx(colliding))).toThrowError(/semantic-text-muted/);
  });

  it('adds a Dark column + Dark Mode section only when a dark document exists', () => {
    const darkDoc = {} as TokensDocument;
    const [file] = emitDesignMd(ctx(light, dark, {} as TokensDocument, darkDoc));
    expect(file!.content).toContain('| Token | Light | Dark |');
    expect(file!.content).toContain('| `color.semantic.bg` | `#fcfcfd` | `#14181f` |');
    expect(file!.content).toContain('## Dark Mode');

    const [lightOnly] = emitDesignMd(ctx(light));
    expect(lightOnly!.content).toContain('| Token | Value |');
    expect(lightOnly!.content).not.toContain('## Dark Mode');
  });

  it('renders spec sections in spec order and extension sections after them', () => {
    const [file] = emitDesignMd(ctx(light, dark, {} as TokensDocument, {} as TokensDocument));
    const order = [
      '## Overview',
      '## Colors',
      '## Typography',
      '## Layout',
      '## Elevation & Depth',
      '## Shapes',
      '## Motion',
      '## Dark Mode',
    ];
    const positions = order.map((heading) => file!.content.indexOf(heading));
    for (const at of positions) expect(at).toBeGreaterThan(-1);
    expect([...positions].sort((a, b) => a - b)).toEqual(positions);
  });

  it('omits empty sections and routes unclassifiable tokens to Other Tokens', () => {
    const minimal = [
      flat(['color', 'semantic', 'bg'], 'color', '#ffffff'),
      flat(['border', 'width'], 'dimension', '1px'),
    ];
    const [file] = emitDesignMd(ctx(minimal));
    expect(file!.content).toContain('## Colors');
    expect(file!.content).not.toContain('## Typography');
    expect(file!.content).not.toContain('## Motion');
    expect(file!.content).toContain('## Other Tokens');
    expect(file!.content).toContain('| `border.width` | `1px` |');
  });

  it('surfaces group $description lines as bullets in the owning section', () => {
    const doc = {
      color: {
        $type: 'color',
        primitive: {
          $description: 'Brand ramp, 12 steps.',
          brand: { '1': { $value: '#fbfcfe' } },
        },
      },
    } as unknown as TokensDocument;
    const [file] = emitDesignMd(ctx(light, [], doc));
    expect(file!.content).toContain('- `color.primitive` - Brand ramp, 12 steps.');
  });

  it('quotes YAML bool/null reserved words so `on`/`yes` keys stay strings', () => {
    const reserved = [
      flat(['color', 'on'], 'color', '#111111'),
      flat(['color', 'yes'], 'color', '#222222'),
    ];
    const [file] = emitDesignMd(ctx(reserved));
    const fm = frontMatter(file!.content);
    expect(fm).toContain('  "on": "#111111"');
    expect(fm).toContain('  "yes": "#222222"');
  });

  it('renders a Notes column with pipes escaped and newlines collapsed', () => {
    const described = [
      flat(['color', 'bg'], 'color', '#ffffff', 'base | surface\ncolor'),
      flat(['color', 'fg'], 'color', '#000000'),
    ];
    const [file] = emitDesignMd(ctx(described));
    expect(file!.content).toContain('| Token | Value | Notes |');
    expect(file!.content).toContain('| `color.bg` | `#ffffff` | base \\| surface color |');
  });

  it('fences names containing a backtick with a double-backtick span', () => {
    const tricky = [flat(['color', 'tick`y'], 'color', '#333333')];
    const [file] = emitDesignMd(ctx(tricky));
    expect(file!.content).toContain('| `` color.tick`y `` | `#333333` |');
  });

  it('mentions modes.dark.json nowhere when there is no overlay', () => {
    const [file] = emitDesignMd(ctx(light));
    expect(file!.content).not.toContain('modes.dark.json');
    expect(file!.content).toContain('# Source of truth: brand/tokens.json.');
  });

  it('omits the Dark Mode section for an overlay with zero actual overrides', () => {
    const [file] = emitDesignMd(ctx(light, [], {} as TokensDocument, {} as TokensDocument));
    expect(file!.content).not.toContain('## Dark Mode');
    expect(file!.content).toContain('modes.dark.json'); // the source mention stays
  });

  it('places a mixed-type group description bullet exactly once (first section wins)', () => {
    const doc = {
      mixed: {
        $description: 'Mixed group.',
        a: { $value: '#123456', $type: 'color' },
        b: { $value: '1px', $type: 'dimension' },
      },
    } as unknown as TokensDocument;
    const tokens = [
      flat(['mixed', 'a'], 'color', '#123456'),
      flat(['mixed', 'b'], 'dimension', '1px'),
    ];
    const [file] = emitDesignMd(ctx(tokens, [], doc));
    const bullet = '- `mixed` - Mixed group.';
    expect(file!.content.indexOf(bullet)).toBe(file!.content.lastIndexOf(bullet));
    expect(file!.content).toContain(bullet);
    expect(file!.content.indexOf(bullet)).toBeLessThan(file!.content.indexOf('## Other Tokens'));
  });

  it('is deterministic: identical input produces identical bytes', () => {
    const [a] = emitDesignMd(ctx(light, dark));
    const [b] = emitDesignMd(ctx(light, dark));
    expect(a!.content).toBe(b!.content);
  });
});

// ---------------------------------------------------------------------------
// Golden byte-match through the PRODUCTION entry point (repo convention:
// every emitter pins its default-preset output in test/golden/).
// ---------------------------------------------------------------------------

const BIN = fileURLToPath(new URL('../bin/onbrand.mjs', import.meta.url));
const GOLDEN = fileURLToPath(new URL('./golden/DESIGN.md', import.meta.url));

const tempDirs: string[] = [];
function tempDir(): string {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'onbrand-designmd-'));
  tempDirs.push(dir);
  return dir;
}
afterAll(() => {
  for (const dir of tempDirs) rmSync(dir, { recursive: true, force: true });
});

function runCli(args: string[]): { status: number | null } {
  const result = spawnSync(process.execPath, [BIN, ...args], { encoding: 'utf8', timeout: 60_000 });
  return { status: result.status };
}

describe('DESIGN.md emitter (spawned through bin/onbrand.mjs)', () => {
  it('matches the committed golden DESIGN.md, byte for byte', () => {
    const dir = tempDir();
    expect(runCli(['init', dir]).status).toBe(EXIT_OK);
    expect(runCli(['build', dir]).status).toBe(EXIT_OK);
    const emitted = readFileSync(path.join(dir, 'brand', 'dist', 'DESIGN.md'), 'utf8');
    expect(emitted).toBe(readFileSync(GOLDEN, 'utf8'));
  });
});
