/**
 * Unit tests for the tokens.py emitter: UPPER_SNAKE naming, the injectivity
 * gate (including the DARK_ prefix and reserved-list collision classes),
 * CHART_CATEGORICAL assembly, and dark-value substitution. The real
 * `python -c "import tokens"` execution harness lives in
 * emitters.e2e.test.ts (integration through the production CLI).
 */

import { describe, expect, it } from 'vitest';
import {
  assertUniquePyNames,
  emitTokensPy,
  tokenPathToPyName,
  tokenValueToPy,
} from '../src/build/emitters/py.ts';
import type { EmitterContext, FlatToken } from '../src/build/compile.ts';
import type { TokensDocument } from '../src/schema/types.ts';

function flat(path: string[], type: FlatToken['type'], value: FlatToken['value']): FlatToken {
  return { path, dotPath: path.join('.'), type, value };
}

function ctx(light: FlatToken[], darkOverrides: FlatToken[] = []): EmitterContext {
  return { light, darkOverrides, lightDocument: {} as TokensDocument };
}

describe('tokenPathToPyName', () => {
  it('upper-snakes dot-path segments', () => {
    expect(tokenPathToPyName(['color', 'semantic', 'bg'])).toBe('COLOR_SEMANTIC_BG');
    expect(tokenPathToPyName(['color', 'semantic', 'text-muted'])).toBe(
      'COLOR_SEMANTIC_TEXT_MUTED',
    );
  });

  it('maps every non-alphanumeric character to "_" (spaces, doubled hyphens)', () => {
    expect(tokenPathToPyName(['type', 'scale', 'step--1'])).toBe('TYPE_SCALE_STEP__1');
    expect(tokenPathToPyName(['color', 'my brand'])).toBe('COLOR_MY_BRAND');
  });

  it('prefixes a leading digit so the name stays a valid Python identifier', () => {
    expect(tokenPathToPyName(['3d', 'depth'])).toBe('N_3D_DEPTH');
  });
});

describe('tokenValueToPy', () => {
  it('renders strings, numbers, lists, and shadow dicts as Python literals', () => {
    expect(tokenValueToPy('#3b63a8')).toBe('"#3b63a8"');
    expect(tokenValueToPy(700)).toBe('700');
    expect(tokenValueToPy(['Inter', 'Segoe UI'])).toBe('["Inter", "Segoe UI"]');
    expect(tokenValueToPy([0.4, 0, 0.2, 1])).toBe('[0.4, 0, 0.2, 1]');
    expect(
      tokenValueToPy({ color: '#0000001f', offsetX: '0px', offsetY: '2px', blur: '8px', spread: '-1px' }),
    ).toBe(
      '{"color": "#0000001f", "offsetX": "0px", "offsetY": "2px", "blur": "8px", "spread": "-1px"}',
    );
  });
});

describe('assertUniquePyNames (the UPPER_SNAKE injectivity gate)', () => {
  it('throws a path-precise error naming BOTH tokens on a flattening collision', () => {
    const colliding = [
      flat(['color', 'semantic', 'text-muted'], 'color', '#566070'),
      flat(['color', 'semantic', 'text', 'muted'], 'color', '#123456'),
    ];
    expect(() => assertUniquePyNames(colliding)).toThrowError(
      /COLOR_SEMANTIC_TEXT_MUTED.*color\.semantic\.text-muted/s,
    );
    expect(() => assertUniquePyNames(colliding)).toThrowError(/color\.semantic\.text\.muted/);
  });

  it('catches the DARK_ prefix collision class (a token group literally named "dark")', () => {
    const colliding = [
      flat(['foo'], 'color', '#111111'),
      flat(['dark', 'foo'], 'color', '#222222'),
    ];
    expect(() => assertUniquePyNames(colliding)).toThrowError(/DARK_FOO/);
    expect(() => assertUniquePyNames(colliding)).toThrowError(/dark-mode constant/);
  });

  it('catches collisions with the reserved CHART_CATEGORICAL list constants', () => {
    const colliding = [flat(['chart', 'categorical'], 'color', '#111111')];
    expect(() => assertUniquePyNames(colliding)).toThrowError(/CHART_CATEGORICAL/);
    expect(() => assertUniquePyNames(colliding)).toThrowError(/reserved list constant/);
  });

  it('accepts a collision-free token set', () => {
    expect(() =>
      assertUniquePyNames([
        flat(['color', 'semantic', 'bg'], 'color', '#fcfcfd'),
        flat(['space', '1'], 'dimension', '0.25rem'),
      ]),
    ).not.toThrow();
  });
});

describe('emitTokensPy', () => {
  const light = [
    flat(['color', 'semantic', 'bg'], 'color', '#fcfcfd'),
    flat(['color', 'chart', 'categorical', '1'], 'color', '#3b63a8'),
    flat(['color', 'chart', 'categorical', '2'], 'color', '#c8571f'),
    flat(['type', 'weight', 'bold'], 'fontWeight', 700),
  ];
  const dark = [
    flat(['color', 'semantic', 'bg'], 'color', '#14181f'),
    flat(['color', 'chart', 'categorical', '1'], 'color', '#6e9bff'),
  ];

  it('starts with the DO-NOT-EDIT header, LF only, trailing newline', () => {
    const [file] = emitTokensPy(ctx(light, dark));
    expect(file!.relPath).toBe('tokens.py');
    expect(file!.content.startsWith('# GENERATED by on-brand - DO NOT EDIT.')).toBe(true);
    expect(file!.content).not.toContain('\r');
    expect(file!.content.endsWith('\n')).toBe(true);
  });

  it('emits light constants, and DARK_ constants for EVERY token (overridden or not)', () => {
    const [file] = emitTokensPy(ctx(light, dark));
    expect(file!.content).toContain('COLOR_SEMANTIC_BG = "#fcfcfd"');
    expect(file!.content).toContain('DARK_COLOR_SEMANTIC_BG = "#14181f"'); // overridden
    expect(file!.content).toContain('TYPE_WEIGHT_BOLD = 700');
    expect(file!.content).toContain('DARK_TYPE_WEIGHT_BOLD = 700'); // carries light value
  });

  it('builds CHART_CATEGORICAL and DARK_CHART_CATEGORICAL from the constants, in order', () => {
    const [file] = emitTokensPy(ctx(light, dark));
    expect(file!.content).toContain(
      'CHART_CATEGORICAL = [\n    COLOR_CHART_CATEGORICAL_1,\n    COLOR_CHART_CATEGORICAL_2,\n]',
    );
    expect(file!.content).toContain(
      'DARK_CHART_CATEGORICAL = [\n    DARK_COLOR_CHART_CATEGORICAL_1,\n    DARK_COLOR_CHART_CATEGORICAL_2,\n]',
    );
  });

  it('emits empty lists when the source has no categorical chart tokens', () => {
    const [file] = emitTokensPy(ctx([flat(['color', 'semantic', 'bg'], 'color', '#fcfcfd')]));
    expect(file!.content).toContain('CHART_CATEGORICAL = []');
    expect(file!.content).toContain('DARK_CHART_CATEGORICAL = []');
  });

  it('refuses to emit a colliding token set (never silent last-wins)', () => {
    const colliding = [
      flat(['color', 'semantic', 'code-bg'], 'color', '#f0f1f4'),
      flat(['color', 'semantic', 'code', 'bg'], 'color', '#ffffff'),
    ];
    expect(() => emitTokensPy(ctx(colliding))).toThrowError(/COLOR_SEMANTIC_CODE_BG/);
  });
});
