/* GENERATED by on-brand - DO NOT EDIT.
 * Source of truth: brand/tokens.json (+ modes.dark.json overlay).
 * Regenerate with `onbrand build`.
 *
 * `theme` holds light values; `darkTheme` is the same shape with dark-mode
 * values (tokens not overridden by modes.dark.json carry their light value).
 * Keys are the exact token names from tokens.json - hyphenated names are
 * quoted, so use bracket access: theme.color.semantic["text-muted"].
 * Values are as authored (tokens.css holds the CSS-ready string forms). */

export const theme = {
  color: {
    primitive: {
      brand: {
        "1": "#fbfcfe",
        "2": "#f5f7fc",
        "3": "#e9eefa",
        "4": "#d9e2f5",
        "5": "#c4d3ef",
        "6": "#a9bfe6",
        "7": "#86a5d9",
        "8": "#5c84c7",
        "9": "#3b63a8",
        "10": "#33569a",
        "11": "#2c4a86",
        "12": "#1a2b4d",
      },
      neutral: {
        "1": "#fcfcfd",
        "2": "#f8f9fa",
        "3": "#f0f1f4",
        "4": "#e7e9ee",
        "5": "#dcdfe6",
        "6": "#ced3dc",
        "7": "#b9c0cc",
        "8": "#99a2b3",
        "9": "#7c8698",
        "10": "#6b7587",
        "11": "#566070",
        "12": "#1f242c",
      },
    },
    semantic: {
      bg: "#fcfcfd",
      surface: "#ffffff",
      text: "#1f242c",
      "text-muted": "#566070",
      border: "#dcdfe6",
      accent: "#3b63a8",
      "code-bg": "#f0f1f4",
      "shadow-color": "#1f242c29",
    },
    status: {
      success: {
        fg: "#166534",
        bg: "#dcfce7",
      },
      warning: {
        fg: "#854d0e",
        bg: "#fef3c7",
      },
      danger: {
        fg: "#991b1b",
        bg: "#fee2e2",
      },
      info: {
        fg: "#1e40af",
        bg: "#dbeafe",
      },
    },
    chart: {
      categorical: {
        "1": "#3b63a8",
        "2": "#c8571f",
        "3": "#2e8b57",
        "4": "#c03434",
        "5": "#7d5ba6",
        "6": "#1f8a8a",
        "7": "#b8860b",
        "8": "#c2578f",
      },
      sequential: {
        "1": "#e9eefa",
        "2": "#c4d3ef",
        "3": "#9db9e6",
        "4": "#6f93cf",
        "5": "#4a6fb0",
        "6": "#33569a",
        "7": "#1a2b4d",
      },
      chrome: {
        grid: "#e7e9ee",
        axis: "#99a2b3",
        label: "#566070",
        "tooltip-bg": "#ffffff",
      },
    },
    diagram: {
      canvas: "#f5f7fc",
      "node-fill": "#ffffff",
      "node-stroke": "#86a5d9",
      link: "#7c8698",
      "spine-accent": "#3b63a8",
      label: "#1f242c",
      "chip-highlight": "#e9eefa",
      warning: "#b45309",
    },
  },
  font: {
    sans: ["Inter", "Segoe UI", "system-ui", "sans-serif"],
    heading: ["Manrope", "Inter", "Segoe UI", "system-ui", "sans-serif"],
    mono: ["JetBrains Mono", "Cascadia Code", "Consolas", "monospace"],
  },
  type: {
    size: {
      base: "1rem",
    },
    scale: {
      "step--1": "clamp(0.8333rem, 0.8101rem + 0.1031vw, 0.9rem)",
      "step-0": "clamp(1rem, 0.9489rem + 0.2273vw, 1.125rem)",
      "step-1": "clamp(1.2rem, 1.131rem + 0.3068vw, 1.4063rem)",
      "step-2": "clamp(1.44rem, 1.3468rem + 0.4141vw, 1.7578rem)",
      "step-3": "clamp(1.728rem, 1.6022rem + 0.5591vw, 2.1973rem)",
      "step-4": "clamp(2.0736rem, 1.9037rem + 0.7547vw, 2.7466rem)",
      "step-5": "clamp(2.4883rem, 2.2593rem + 1.0182vw, 3.4332rem)",
    },
    weight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    "line-height": {
      tight: 1.2,
      base: 1.55,
      loose: 1.7,
    },
  },
  space: {
    "1": "0.25rem",
    "2": "0.5rem",
    "3": "0.75rem",
    "4": "1rem",
    "5": "1.5rem",
    "6": "2rem",
    "7": "2.5rem",
    "8": "3rem",
    "9": "4rem",
    "10": "6rem",
  },
  radius: {
    sm: "4px",
    md: "8px",
    lg: "12px",
    pill: "999px",
  },
  shadow: {
    "elevation-1": { color: "#1f242c14", offsetX: "0px", offsetY: "1px", blur: "2px", spread: "0px" },
    "elevation-2": { color: "#1f242c1f", offsetX: "0px", offsetY: "2px", blur: "8px", spread: "-1px" },
    "elevation-3": { color: "#1f242c29", offsetX: "0px", offsetY: "8px", blur: "24px", spread: "-4px" },
  },
  motion: {
    duration: {
      fast: "120ms",
      base: "200ms",
      slow: "400ms",
    },
    easing: {
      standard: [0.4, 0, 0.2, 1],
      decelerate: [0, 0, 0.2, 1],
      accelerate: [0.4, 0, 1, 1],
    },
  },
} as const;

export const darkTheme = {
  color: {
    primitive: {
      brand: {
        "1": "#0e1523",
        "2": "#121a2b",
        "3": "#16223a",
        "4": "#1b2b4a",
        "5": "#213659",
        "6": "#2a4370",
        "7": "#365490",
        "8": "#4568ae",
        "9": "#5c8ae6",
        "10": "#6e9bff",
        "11": "#93b4f2",
        "12": "#dbe6fb",
      },
      neutral: {
        "1": "#14181f",
        "2": "#171c24",
        "3": "#1d232d",
        "4": "#232a35",
        "5": "#2a323e",
        "6": "#333c4a",
        "7": "#40495a",
        "8": "#566070",
        "9": "#6b7587",
        "10": "#7c8698",
        "11": "#a4adbc",
        "12": "#edeff3",
      },
    },
    semantic: {
      bg: "#14181f",
      surface: "#1d232d",
      text: "#edeff3",
      "text-muted": "#a4adbc",
      border: "#333c4a",
      accent: "#6e9bff",
      "code-bg": "#232a35",
      "shadow-color": "#00000080",
    },
    status: {
      success: {
        fg: "#7ee2a8",
        bg: "#12301f",
      },
      warning: {
        fg: "#e6b95c",
        bg: "#33270e",
      },
      danger: {
        fg: "#f2a49c",
        bg: "#3a1715",
      },
      info: {
        fg: "#8ab8f8",
        bg: "#14263f",
      },
    },
    chart: {
      categorical: {
        "1": "#6e9bff",
        "2": "#e8975a",
        "3": "#5fbd88",
        "4": "#ee8277",
        "5": "#b195dd",
        "6": "#54bdbd",
        "7": "#d9b24a",
        "8": "#e08ebc",
      },
      sequential: {
        "1": "#16223a",
        "2": "#1f3054",
        "3": "#2c4576",
        "4": "#3f5d97",
        "5": "#5c7fc0",
        "6": "#8aa8e0",
        "7": "#c4d5f5",
      },
      chrome: {
        grid: "#2a323e",
        axis: "#7c8698",
        label: "#b9c0cc",
        "tooltip-bg": "#1d232d",
      },
    },
    diagram: {
      canvas: "#161c26",
      "node-fill": "#1f2733",
      "node-stroke": "#6e9bff",
      link: "#566070",
      "spine-accent": "#6e9bff",
      label: "#e7e9ee",
      "chip-highlight": "#23304a",
      warning: "#e3a542",
    },
  },
  font: {
    sans: ["Inter", "Segoe UI", "system-ui", "sans-serif"],
    heading: ["Manrope", "Inter", "Segoe UI", "system-ui", "sans-serif"],
    mono: ["JetBrains Mono", "Cascadia Code", "Consolas", "monospace"],
  },
  type: {
    size: {
      base: "1rem",
    },
    scale: {
      "step--1": "clamp(0.8333rem, 0.8101rem + 0.1031vw, 0.9rem)",
      "step-0": "clamp(1rem, 0.9489rem + 0.2273vw, 1.125rem)",
      "step-1": "clamp(1.2rem, 1.131rem + 0.3068vw, 1.4063rem)",
      "step-2": "clamp(1.44rem, 1.3468rem + 0.4141vw, 1.7578rem)",
      "step-3": "clamp(1.728rem, 1.6022rem + 0.5591vw, 2.1973rem)",
      "step-4": "clamp(2.0736rem, 1.9037rem + 0.7547vw, 2.7466rem)",
      "step-5": "clamp(2.4883rem, 2.2593rem + 1.0182vw, 3.4332rem)",
    },
    weight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    "line-height": {
      tight: 1.2,
      base: 1.55,
      loose: 1.7,
    },
  },
  space: {
    "1": "0.25rem",
    "2": "0.5rem",
    "3": "0.75rem",
    "4": "1rem",
    "5": "1.5rem",
    "6": "2rem",
    "7": "2.5rem",
    "8": "3rem",
    "9": "4rem",
    "10": "6rem",
  },
  radius: {
    sm: "4px",
    md: "8px",
    lg: "12px",
    pill: "999px",
  },
  shadow: {
    "elevation-1": { color: "#1f242c14", offsetX: "0px", offsetY: "1px", blur: "2px", spread: "0px" },
    "elevation-2": { color: "#1f242c1f", offsetX: "0px", offsetY: "2px", blur: "8px", spread: "-1px" },
    "elevation-3": { color: "#1f242c29", offsetX: "0px", offsetY: "8px", blur: "24px", spread: "-4px" },
  },
  motion: {
    duration: {
      fast: "120ms",
      base: "200ms",
      slow: "400ms",
    },
    easing: {
      standard: [0.4, 0, 0.2, 1],
      decelerate: [0, 0, 0.2, 1],
      accelerate: [0.4, 0, 1, 1],
    },
  },
} as const;

export type Theme = typeof theme;
export type DarkTheme = typeof darkTheme;
