/**
 * Pure, deterministic standalone renderer for inspiration-to-implementation.
 *
 * This screen answers a deliberately narrower question than `specimen.html`:
 * where did the palette come from, and how did it become actual tokens?  The
 * full specimen remains the broad component/system validation screen.  The
 * page is overview-first: a source image and active-mode palette are visible
 * together, with the audit record behind native progressive disclosure.
 */

import { INSPIRATION_LIMITS, type InspirationAsset } from './contract.ts';
import type {
  ResolvedDefaultDerivedTarget,
  ResolvedInspirationMapping,
  ResolvedInspirationTarget,
  ResolvedInspirationTrace,
} from './resolve.ts';

export class InspirationRenderError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'InspirationRenderError';
  }
}

/** Escape text and attributes; all dynamic prose goes through this one seam. */
export function escapeInspirationHtml(value: string): string {
  let out = '';
  for (let index = 0; index < value.length; index++) {
    const char = value[index]!;
    if (char === '&') out += '&amp;';
    else if (char === '<') out += '&lt;';
    else if (char === '>') out += '&gt;';
    else if (char === '"') out += '&quot;';
    else if (char === "'") out += '&#39;';
    else out += char;
  }
  return out;
}

/** Render the complete portable HTML page, or fail before an oversized write. */
export function renderInspirationHtml(model: ResolvedInspirationTrace): string {
  const trace = model.trace;
  const resolvedTargets = [
    ...model.mappings.flatMap((mapping) => mapping.targets),
    ...model.defaultDerivedColorTargets,
  ];
  const hasDarkMode = resolvedTargets.length > 0
    && resolvedTargets.every((target) => target.darkHex !== null);
  const assetHeightCqw = containmentPercentage(model.asset.height / model.asset.width);
  const assetHalfHeightCqw = containmentPercentage(model.asset.height / model.asset.width / 2);
  const assetBorderHeightCqw = containmentPercentage(model.asset.height / model.asset.width / 8);
  // Keep this data URI in exactly one initial DOM node. The zoom dialog copies
  // it lazily when opened, avoiding a second 5MB asset in the 8MB HTML cap.
  const embeddedAsset = `data:${model.asset.mediaType};base64,${Buffer.from(model.asset.bytes).toString('base64')}`;
  const pins = model.mappings.map((mapping, index) => renderPin(mapping, index + 1)).join('\n');
  const paletteOverview = renderPaletteOverview(model.mappings);
  const mappingCards = model.mappings.map((mapping, index) => renderMappingCard(mapping, index + 1)).join('\n');
  const unobserved = trace.analysis.unobservedDefaults.map((value) => `<li>${escapeInspirationHtml(value)}</li>`).join('');
  const defaultDerived = model.defaultDerivedColorTargets.length === 0
    ? '<p class="muted">No categorical or diagram slots were default-derived.</p>'
    : `<ul class="default-list">${model.defaultDerivedColorTargets.map(renderDefaultDerived).join('')}</ul>`;
  const sourceLinks = renderAttributionLinks(trace.asset);

  const html = `<!doctype html>
<html lang="en" data-theme="light">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark">
    <title>${escapeInspirationHtml(trace.asset.title)} — inspiration to implementation</title>
    <!-- GENERATED by on-brand. Source: brand/inspiration.json. DO NOT EDIT. -->
    <style>
      :root { color-scheme: light; font-family: system-ui, sans-serif; line-height: 1.5; }
      *, *::before, *::after { box-sizing: border-box; }
      body { margin: 0; background: #f7f8fa; color: #1c2028; }
      img { max-width: 100%; }
      a { color: #0645ad; }
      a:focus-visible, button:focus-visible, summary:focus-visible { outline: 3px solid #005fcc; outline-offset: 3px; }
      .page { width: min(1280px, calc(100% - 32px)); margin: 0 auto; padding: 24px 0 56px; }
      header { display: grid; grid-template-columns: minmax(0, 1fr) max-content; gap: 10px 24px; align-items: end; margin-bottom: 20px; }
      .header-copy { min-width: 0; }
      h1, h2, h3, p { margin-top: 0; }
      h1 { font-size: clamp(1.8rem, 4vw, 2.7rem); line-height: 1.1; margin-bottom: 8px; }
      h2 { font-size: 1.35rem; line-height: 1.2; }
      h3 { font-size: 1rem; margin-bottom: 8px; }
      .eyebrow, .muted, .token-path, .value, .mode-note { color: #5b6470; font-size: .92rem; }
      .status { display: inline-flex; width: max-content; border: 1px solid #68707b; border-radius: 999px; padding: 3px 10px; font-size: .86rem; }
      .theme-toggle { display: inline-flex; align-items: center; justify-content: center; max-width: 100%; min-height: 40px; border: 1px solid #1c2028; border-radius: 8px; padding: 8px 12px; color: #fff; background: #1c2028; font: inherit; cursor: pointer; }
      .layout { display: grid; grid-template-columns: minmax(330px, .84fr) minmax(0, 1.16fr); column-gap: 24px; row-gap: 0; align-items: start; isolation: isolate; }
      .layout::before, .layout::after { content: ''; grid-row: 1 / span 2; align-self: stretch; z-index: 0; border: 1px solid #d5d9df; border-radius: 14px; background: #fff; box-shadow: 0 2px 8px rgb(0 0 0 / 8%); pointer-events: none; }
      .layout::before { grid-column: 1; }
      .layout::after { grid-column: 2; }
      .source-primary, .source-secondary, .implementation-primary, .implementation-secondary { position: relative; z-index: 1; min-width: 0; }
      .source-primary { grid-column: 1; grid-row: 1; padding: 18px 18px 0; }
      .implementation-primary { grid-column: 2; grid-row: 1; padding: 18px 18px 0; }
      .source-secondary { grid-column: 1; grid-row: 2; padding: 14px 18px 18px; }
      .implementation-secondary { grid-column: 2; grid-row: 2; padding: 14px 18px 18px; }
      .image-wrap { position: relative; overflow: hidden; container-type: inline-size; border: 1px solid #b9c0ca; border-radius: 10px; background: #e7ebf0; }
      .image-wrap > img { display: block; width: 100%; height: auto; }
      .image-button { position: absolute; z-index: 1; inset: 0; display: block; width: 100%; padding: 0; border: 0; background: transparent; cursor: zoom-in; }
      .image-button:focus-visible { outline: 4px solid #005fcc; outline-offset: -6px; box-shadow: inset 0 0 0 2px #fff; }
      .zoom-hint { position: absolute; z-index: 2; right: 10px; bottom: 10px; margin: 0; border-radius: 999px; padding: 4px 9px; color: #fff; background: rgb(28 32 40 / 86%); font-size: .82rem; pointer-events: none; }
      .pin { position: absolute; z-index: 2; transform: translate(-50%, -50%); display: grid; place-items: center; width: var(--pin-size); height: var(--pin-size); overflow: hidden; border: var(--pin-border) solid #fff; border-radius: 50%; background: #1c2028; color: #fff; font: 700 min(13px, var(--pin-size))/1 system-ui, sans-serif; box-shadow: 0 1px 4px rgb(0 0 0 / 35%); pointer-events: none; }
      .source-details-heading { margin-bottom: 8px; }
      .metadata { display: grid; grid-template-columns: max-content 1fr; gap: 5px 12px; margin: 14px 0 0; }
      .metadata dt { color: #5b6470; font-weight: 600; }
      .metadata dd { margin: 0; overflow-wrap: anywhere; }
      .screen-purpose { margin-bottom: 15px; }
      .palette-overview { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; }
      .palette-item { min-width: 0; border: 1px solid #d5d9df; border-radius: 9px; padding: 10px; }
      .palette-item-top { display: flex; align-items: center; gap: 7px; }
      .palette-copy { min-width: 0; }
      .palette-label { display: block; font-size: .82rem; line-height: 1.2; overflow-wrap: anywhere; }
      .number { display: inline-grid; place-items: center; flex: 0 0 auto; width: 25px; height: 25px; border-radius: 50%; background: #1c2028; color: #fff; font-weight: 700; font-size: .8rem; }
      .swatch { width: 30px; height: 30px; border: 1px solid #68707b; border-radius: 6px; background: var(--sample); flex: 0 0 auto; }
      .sample-hex, .mode-hex { display: block; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: .79rem; overflow-wrap: anywhere; }
      .palette-targets { display: flex; flex-wrap: wrap; gap: 5px; margin-top: 9px; }
      .palette-target { width: 22px; height: 22px; border: 1px solid #68707b; border-radius: 4px; background: var(--light); }
      [data-theme="dark"] .palette-target { background: var(--dark); }
      .mode-note { margin: 12px 0 0; }
      .mode-description { margin-left: .35em; }
      .no-js-note { margin: 0 0 14px; border: 1px solid #68707b; border-radius: 9px; padding: 9px 11px; background: #fff; }
      details { border: 1px solid #d5d9df; border-radius: 10px; background: rgb(247 248 250 / 62%); }
      details + details { margin-top: 12px; }
      summary { cursor: pointer; padding: 12px 14px; font-weight: 700; }
      .details-body { padding: 0 14px 14px; }
      .mapping-list { display: grid; gap: 12px; }
      .mapping { border: 1px solid #d5d9df; border-radius: 10px; padding: 13px; background: #fff; }
      .mapping-head { display: flex; align-items: center; gap: 10px; margin-bottom: 9px; }
      .sample { display: flex; gap: 10px; align-items: center; margin-bottom: 10px; }
      .targets { display: grid; gap: 10px; }
      .target { border-top: 1px solid #e2e5e9; padding-top: 10px; }
      .target:first-child { border-top: 0; padding-top: 0; }
      .target-top { display: flex; justify-content: space-between; gap: 10px; align-items: baseline; flex-wrap: wrap; }
      .token-path { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; overflow-wrap: anywhere; }
      .relationship { font-size: .82rem; font-weight: 600; }
      .value { display: grid; grid-template-columns: 20px minmax(0, 1fr); gap: 7px; align-items: center; margin: 8px 0; }
      .value-swatch { width: 20px; height: 20px; border: 1px solid #68707b; border-radius: 4px; background: var(--light); }
      [data-theme="dark"] .value-swatch { background: var(--dark); }
      .value code { color: #1c2028; font-size: .86rem; }
      .light-value { display: inline; }
      .dark-value { display: none; }
      [data-theme="dark"] .light-value { display: none; }
      [data-theme="dark"] .dark-value { display: inline; }
      .recipe { display: flex; align-items: center; min-height: 34px; margin-top: 8px; }
      .recipe-shape { background: var(--light); border: 1px solid #68707b; }
      [data-theme="dark"] .recipe-shape { background: var(--dark); }
      .recipe-surface { width: 74px; height: 32px; border-radius: 5px; }
      .recipe-text { width: 94px; height: 8px; border-radius: 999px; }
      .recipe-button-bg { width: 76px; height: 30px; border-radius: 999px; }
      .recipe-badge-bg { width: 50px; height: 20px; border-radius: 999px; }
      .recipe-chart-series { width: 90px; height: 20px; clip-path: polygon(0 80%, 22% 50%, 46% 64%, 72% 18%, 100% 34%, 100% 100%, 0 100%); }
      .recipe-swatch-only { width: 30px; height: 30px; border-radius: 50%; }
      .usage { margin: 8px 0 0; font-size: .92rem; }
      .rationale { margin: 10px 0 0; font-size: .92rem; }
      .unobserved { display: flex; flex-wrap: wrap; padding: 0; gap: 7px; list-style: none; }
      .unobserved li { border: 1px solid #b9c0ca; border-radius: 999px; padding: 3px 9px; font-size: .86rem; }
      .default-list { display: grid; gap: 9px; padding-left: 20px; }
      .default-list li { padding-left: 2px; }
      .action { display: inline-block; max-width: 100%; margin-top: 14px; border: 1px solid #1c2028; border-radius: 7px; padding: 8px 11px; color: #fff; background: #1c2028; text-decoration: none; overflow-wrap: anywhere; }
      dialog { width: min(1100px, calc(100% - 28px)); max-height: calc(100% - 28px); padding: 0; border: 1px solid #68707b; border-radius: 14px; color: inherit; background: #fff; box-shadow: 0 18px 60px rgb(0 0 0 / 45%); }
      dialog::backdrop { background: rgb(0 0 0 / 62%); }
      .dialog-head { display: flex; justify-content: space-between; gap: 12px; align-items: center; padding: 12px 14px; border-bottom: 1px solid #d5d9df; }
      .dialog-controls { display: flex; gap: 8px; flex-wrap: wrap; }
      .dialog-controls button { border: 1px solid #68707b; border-radius: 7px; padding: 7px 10px; color: inherit; background: transparent; font: inherit; cursor: pointer; }
      .zoom-stage { overflow: auto; max-height: min(76vh, 800px); padding: 16px; background: #e7ebf0; }
      .zoom-stage img { display: block; width: 100%; height: auto; transform-origin: top left; }
      .zoom-stage.is-zoomed img { width: 200%; max-width: none; }
      .sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; }
      [data-theme="dark"] { color-scheme: dark; }
      [data-theme="dark"] body {
        background: #15181d;
        color: #edf0f4;
      }
      [data-theme="dark"] a { color: #8ab4ff; }
      [data-theme="dark"] .theme-toggle { color: #1c2028; background: #edf0f4; }
      [data-theme="dark"] .layout::before,
      [data-theme="dark"] .layout::after,
      [data-theme="dark"] .mapping,
      [data-theme="dark"] .no-js-note { background: #20242b; border-color: #515966; box-shadow: none; }
      [data-theme="dark"] details { background: #1a1e25; border-color: #515966; }
      [data-theme="dark"] .palette-item,
      [data-theme="dark"] .target,
      [data-theme="dark"] .dialog-head { border-color: #515966; }
      [data-theme="dark"] .target { border-color: #404752; }
      [data-theme="dark"] .eyebrow,
      [data-theme="dark"] .muted,
      [data-theme="dark"] .token-path,
      [data-theme="dark"] .value,
      [data-theme="dark"] .metadata dt,
      [data-theme="dark"] .mode-note { color: #b3bac5; }
      [data-theme="dark"] .value code { color: #edf0f4; }
      [data-theme="dark"] .status,
      [data-theme="dark"] .swatch,
      [data-theme="dark"] .value-swatch,
      [data-theme="dark"] .recipe-shape,
      [data-theme="dark"] .unobserved li,
      [data-theme="dark"] .palette-target { border-color: #a9b2bf; }
      [data-theme="dark"] dialog { color: #edf0f4; background: #20242b; border-color: #a9b2bf; }
      [data-theme="dark"] .zoom-stage { background: #11141a; }
      @media (max-width: 900px) {
        .page { width: min(100% - 24px, 720px); padding-top: 20px; }
        .layout { grid-template-columns: minmax(0, 1fr); gap: 12px; isolation: auto; }
        .layout::before, .layout::after { display: none; }
        .source-primary, .implementation-primary, .source-secondary, .implementation-secondary { grid-column: 1; grid-row: auto; padding: 16px; border: 1px solid #d5d9df; border-radius: 14px; background: #fff; box-shadow: 0 2px 8px rgb(0 0 0 / 8%); }
        [data-theme="dark"] .source-primary,
        [data-theme="dark"] .implementation-primary,
        [data-theme="dark"] .source-secondary,
        [data-theme="dark"] .implementation-secondary { background: #20242b; border-color: #515966; box-shadow: none; }
        .palette-overview { grid-template-columns: repeat(2, minmax(0, 1fr)); }
      }
      @media (max-width: 520px) {
        .page { width: calc(100% - 16px); padding: 10px 0 36px; }
        header { grid-template-columns: 1fr; gap: 7px; margin-bottom: 10px; }
        .header-copy > .eyebrow { margin-bottom: 3px; }
        h1 { font-size: 1.65rem; margin-bottom: 4px; }
        h2 { font-size: 1.12rem; margin-bottom: 8px; }
        .header-copy > p:not(.eyebrow) { margin-bottom: 7px; font-size: .9rem; line-height: 1.35; }
        .status { max-width: 100%; padding: 2px 8px; font-size: .78rem; overflow-wrap: anywhere; }
        .theme-toggle { width: max-content; min-height: 34px; padding: 5px 9px; font-size: .85rem; }
        .layout { gap: 10px; }
        .source-primary, .implementation-primary, .source-secondary, .implementation-secondary { border-radius: 11px; padding: 10px; }
        .palette-overview { grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 6px; }
        .palette-item { border-radius: 7px; padding: 6px; }
        .palette-item-top { gap: 4px; }
        .number { width: 20px; height: 20px; font-size: .7rem; }
        .swatch { width: 24px; height: 24px; }
        .palette-label { font-size: .7rem; }
        .sample-hex { font-size: .69rem; }
        .palette-targets { gap: 3px; margin-top: 5px; }
        .palette-target { width: 17px; height: 17px; }
        .mode-note { margin: 6px 0 8px; font-size: .78rem; line-height: 1.25; }
        .mode-description { display: block; margin: 2px 0 0; }
        .metadata { grid-template-columns: minmax(0, max-content) minmax(0, 1fr); margin-top: 0; font-size: .9rem; }
        .dialog-head { align-items: flex-start; flex-direction: column; }
      }
      @media (prefers-reduced-motion: reduce) { *, *::before, *::after { scroll-behavior: auto !important; transition: none !important; animation: none !important; } }
    </style>
    <noscript><style>#theme-toggle, #image-zoom-open, .zoom-hint { display: none !important; } .light-value, .dark-value { display: inline !important; } .dark-value { margin-left: .45em; }</style></noscript>
  </head>
  <body>
    <main class="page">
      <header>
        <div class="header-copy">
          <p class="eyebrow">Inspiration to implementation</p>
          <h1>${escapeInspirationHtml(trace.asset.title)}</h1>
          <p>${escapeInspirationHtml(trace.summary)}</p>
          <span class="status">Review status: ${escapeInspirationHtml(trace.reviewStatus)}</span>
        </div>
        <button id="theme-toggle" class="theme-toggle" type="button" aria-pressed="false" aria-controls="palette-overview mode-status">Switch to dark</button>
      </header>
      <noscript><p class="no-js-note" role="note"><strong>Static view:</strong> The summary uses light implementation colors. Theme switching and image zoom require JavaScript; open the native mapping or defaults details to read both resolved light and dark values.</p></noscript>
      <div class="layout">
        <section class="source-primary" aria-labelledby="inspiration-heading">
          <h2 id="inspiration-heading">Inspiration</h2>
          <div class="image-wrap" style="--pin-size:min(28px,100cqw,${assetHeightCqw}cqw);--pin-radius:min(14px,50cqw,${assetHalfHeightCqw}cqw);--pin-border:min(2px,12.5cqw,${assetBorderHeightCqw}cqw)">
            <img id="inspiration-image" src="${embeddedAsset}" alt="${escapeInspirationHtml(trace.asset.alt)}">
            <button id="image-zoom-open" class="image-button" type="button" aria-haspopup="dialog" aria-controls="image-zoom-dialog" aria-label="Expand and zoom the inspiration image"></button>
${pins}
            <p class="zoom-hint" aria-hidden="true">Click to expand and zoom</p>
          </div>
          <ol class="sr-only source-pin-fallback" aria-label="Numbered source sample key">${model.mappings.map((mapping, index) => `<li id="source-pin-fallback-${index + 1}" data-mapping-number="${index + 1}">${index + 1}. ${escapeInspirationHtml(mapping.label)}: ${escapeInspirationHtml(mapping.sample.hex)}</li>`).join('')}</ol>
        </section>
        <section class="implementation-primary" aria-labelledby="implementation-heading">
          <h2 id="implementation-heading">Palette summary</h2>
          <p id="mode-status" class="mode-note" aria-live="polite"><strong id="mode-label" class="mode-label">Light implementation</strong><span id="mode-description" class="mode-description">${hasDarkMode ? 'Showing resolved light token values.' : 'No dark mode file was resolved; dark previews reuse these light token values.'}</span></p>
          <div id="palette-overview" class="palette-overview" aria-label="Numbered source palette and active-mode implementation palette">
${paletteOverview}
          </div>
        </section>
        <section class="source-secondary" aria-labelledby="source-details-heading">
          <h3 id="source-details-heading" class="source-details-heading">Source details</h3>
          <dl class="metadata">
            <dt>Description</dt><dd class="asset-alt">${escapeInspirationHtml(trace.asset.alt)}</dd>
            <dt>Creator</dt><dd>${escapeInspirationHtml(trace.asset.creator)}</dd>
            <dt>Title</dt><dd>${escapeInspirationHtml(trace.asset.title)}</dd>
            <dt>Date</dt><dd>${escapeInspirationHtml(trace.asset.date)}</dd>
            <dt>Rights</dt><dd>${escapeInspirationHtml(trace.asset.rights)}</dd>
            <dt>Image size</dt><dd>${model.asset.width} × ${model.asset.height}px</dd>
${sourceLinks}
          </dl>
        </section>
        <section class="implementation-secondary" aria-label="Implementation evidence and specimen handoff">
          <p class="screen-purpose">This screen traces measured image colors to implemented tokens. The linked specimen is the separate full component-system check.</p>
          <details class="mapping-details">
            <summary>Mapping details (${model.mappings.length})</summary>
            <div class="details-body">
              <p class="muted">Every measured sample, target token, transformation, and use is retained here for review.</p>
              <div class="mapping-list">
${mappingCards}
              </div>
            </div>
          </details>
          <details class="defaults">
            <summary>Defaults not evidenced by the image</summary>
            <div class="details-body">
              <p class="muted">The image provides no direct evidence for these design choices.</p>
              <ul class="unobserved">${unobserved}</ul>
              <h3>Default-derived categorical and diagram slots</h3>
${defaultDerived}
            </div>
          </details>
          <a class="action" href="specimen.html">Open full component specimen</a>
        </section>
      </div>
    </main>
    <dialog id="image-zoom-dialog" aria-labelledby="image-zoom-title">
      <div class="dialog-head">
        <strong id="image-zoom-title">Inspect inspiration image</strong>
        <div class="dialog-controls">
          <button id="image-zoom-toggle" type="button" aria-pressed="false">Zoom to 200%</button>
          <button id="image-zoom-close" type="button">Close</button>
        </div>
      </div>
      <div id="image-zoom-stage" class="zoom-stage"><img id="image-zoom-image" alt="${escapeInspirationHtml(trace.asset.alt)}"></div>
    </dialog>
    <script>
      (function () {
        var root = document.documentElement;
        var themeButton = document.getElementById('theme-toggle');
        var dialog = document.getElementById('image-zoom-dialog');
        var openButton = document.getElementById('image-zoom-open');
        var closeButton = document.getElementById('image-zoom-close');
        var zoomButton = document.getElementById('image-zoom-toggle');
        var sourceImage = document.getElementById('inspiration-image');
        var zoomImage = document.getElementById('image-zoom-image');
        var zoomStage = document.getElementById('image-zoom-stage');
        var modeLabel = document.getElementById('mode-label');
        var modeDescription = document.getElementById('mode-description');
        var hasDarkMode = ${hasDarkMode ? 'true' : 'false'};
        function applyTheme(theme) {
          root.setAttribute('data-theme', theme);
          themeButton.setAttribute('aria-pressed', theme === 'dark' ? 'true' : 'false');
          themeButton.textContent = theme === 'dark' ? 'Switch to light' : 'Switch to dark';
          modeLabel.textContent = theme === 'dark' ? 'Dark implementation' : 'Light implementation';
          modeDescription.textContent = theme === 'dark'
            ? (hasDarkMode ? 'Showing resolved dark token values.' : 'No dark mode file was resolved; these swatches reuse light token values.')
            : (hasDarkMode ? 'Showing resolved light token values.' : 'No dark mode file was resolved; dark previews reuse these light token values.');
        }
        themeButton.addEventListener('click', function () {
          applyTheme(root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark');
        });
        openButton.addEventListener('click', function () {
          zoomImage.src = sourceImage.currentSrc || sourceImage.src;
          zoomImage.alt = sourceImage.alt;
          zoomStage.classList.remove('is-zoomed');
          zoomButton.setAttribute('aria-pressed', 'false');
          zoomButton.textContent = 'Zoom to 200%';
          dialog.showModal();
          closeButton.focus();
        });
        closeButton.addEventListener('click', function () { dialog.close(); });
        dialog.addEventListener('close', function () {
          if (openButton.isConnected) openButton.focus();
        });
        zoomButton.addEventListener('click', function () {
          var zoomed = zoomStage.classList.toggle('is-zoomed');
          zoomButton.setAttribute('aria-pressed', zoomed ? 'true' : 'false');
          zoomButton.textContent = zoomed ? 'Fit image' : 'Zoom to 200%';
        });
      })();
    </script>
  </body>
</html>
`;
  if (Buffer.byteLength(html, 'utf8') > INSPIRATION_LIMITS.maxStandaloneHtmlBytes) {
    throw new InspirationRenderError(
      `rendered inspiration page exceeds ${INSPIRATION_LIMITS.maxStandaloneHtmlBytes} UTF-8 bytes`,
    );
  }
  return html;
}

function renderPin(mapping: ResolvedInspirationMapping, number: number): string {
  const x = percentage(mapping.region.x + mapping.region.width / 2);
  const y = percentage(mapping.region.y + mapping.region.height / 2);
  return `            <span id="source-pin-${number}" class="pin" role="img" aria-label="Source sample ${number}" aria-describedby="source-pin-fallback-${number}" aria-details="mapping-detail-${number}" data-mapping-number="${number}" style="left:clamp(var(--pin-radius),${x}%,calc(100% - var(--pin-radius)));top:clamp(var(--pin-radius),${y}%,calc(100% - var(--pin-radius)))">${number}</span>`;
}

/** Compact, one-viewport summary: source swatch plus every active token swatch. */
function renderPaletteOverview(mappings: readonly ResolvedInspirationMapping[]): string {
  return mappings.map((mapping, index) => {
    const targets = mapping.targets.map((target) => {
      const dark = target.darkHex ?? target.lightHex;
      return `<span class="palette-target" title="${escapeInspirationHtml(target.token)}" aria-label="${escapeInspirationHtml(target.token)}: light ${target.lightHex}, dark ${dark}" style="--light:${target.lightHex};--dark:${dark}"></span>`;
    }).join('');
    const number = index + 1;
    return `              <article id="palette-item-${number}" class="palette-item" aria-labelledby="palette-number-${number} palette-label-${number}" aria-describedby="palette-source-${number}" aria-details="mapping-detail-${number}" data-mapping-number="${number}">
              <div class="palette-item-top"><span id="palette-number-${number}" class="number">${number}</span><span class="swatch" aria-hidden="true" style="--sample:${mapping.sample.hex}"></span><span class="palette-copy"><strong id="palette-label-${number}" class="palette-label">${escapeInspirationHtml(mapping.label)}</strong><span id="palette-source-${number}" class="sample-hex">${escapeInspirationHtml(mapping.sample.hex)} source</span></span></div>
              <div class="palette-targets">${targets}</div>
            </article>`;
  }).join('\n');
}

function renderMappingCard(mapping: ResolvedInspirationMapping, number: number): string {
  const targets = mapping.targets.map((target) => renderTarget(target)).join('\n');
  return `                <article id="mapping-detail-${number}" class="mapping" aria-labelledby="mapping-detail-number-${number} mapping-${number}" data-mapping-number="${number}">
                  <div class="mapping-head"><span id="mapping-detail-number-${number}" class="number">${number}</span><h3 id="mapping-${number}">${escapeInspirationHtml(mapping.label)}</h3></div>
                  <div class="sample"><span class="swatch" aria-hidden="true" style="--sample:${mapping.sample.hex}"></span><span><strong>Measured source sample</strong><br><code>${escapeInspirationHtml(mapping.sample.hex)}</code> · ${formatPercent(mapping.sample.pixelShare)}% of working pixels · ${escapeInspirationHtml(mapping.confidence)} confidence</span></div>
                  <div class="targets">
${targets}
                  </div>
                  <p class="rationale"><strong>Why this mapping:</strong> ${escapeInspirationHtml(mapping.rationale)}</p>
                </article>`;
}

function renderTarget(target: ResolvedInspirationTarget): string {
  const dark = target.darkHex ?? target.lightHex;
  const darkText = target.darkHex === null ? 'no dark mode file; using light value' : target.darkHex;
  return `                    <div class="target">
                      <div class="target-top"><code class="token-path">${escapeInspirationHtml(target.token)}</code><span class="relationship">${escapeInspirationHtml(target.relationship)}</span></div>
                      <span class="value"><span class="value-swatch" aria-hidden="true" style="--light:${target.lightHex};--dark:${dark}"></span><span><span class="light-value">Light: <code>${target.lightHex}</code></span><span class="dark-value">Dark: <code>${darkText}</code></span></span></span>
                      <div class="recipe" aria-label="Compact ${escapeInspirationHtml(target.presentation)} token silhouette"><span class="recipe-shape recipe-${escapeInspirationHtml(target.presentation)}" aria-hidden="true" style="--light:${target.lightHex};--dark:${dark}"></span></div>
                      <p class="usage"><strong>Usage:</strong> ${escapeInspirationHtml(target.usage)}</p>
                    </div>`;
}

function renderDefaultDerived(target: ResolvedDefaultDerivedTarget): string {
  const dark = target.darkHex ?? target.lightHex;
  const darkText = target.darkHex === null ? 'no dark mode file; using light value' : target.darkHex;
  return `<li><code class="token-path">${escapeInspirationHtml(target.token)}</code> — ${escapeInspirationHtml(target.role)}, ${escapeInspirationHtml(target.reason)}; <span class="light-value">light ${target.lightHex}</span><span class="dark-value">dark ${darkText}</span><span class="sr-only">; alternate mode is ${dark}</span>.</li>`;
}

function renderAttributionLinks(asset: InspirationAsset): string {
  const rows: string[] = [];
  if (asset.sourceUrl !== null) {
    rows.push(`<dt>Source</dt><dd><a href="${escapeInspirationHtml(asset.sourceUrl)}" rel="noopener noreferrer" target="_blank">Open source</a></dd>`);
  }
  if (asset.licenseUrl !== null) {
    rows.push(`<dt>License</dt><dd><a href="${escapeInspirationHtml(asset.licenseUrl)}" rel="noopener noreferrer" target="_blank">Open license</a></dd>`);
  }
  if (asset.retrievedAt !== null) rows.push(`<dt>Retrieved</dt><dd>${escapeInspirationHtml(asset.retrievedAt)}</dd>`);
  return rows.length === 0 ? '' : `            ${rows.join('\n            ')}`;
}

function percentage(value: number): string {
  // Region bounds are validated in contract.ts. Rounding remains deterministic
  // and keeps the generated source readable rather than serialising binary FP.
  return String(Math.round(value * 10_000) / 100);
}

function formatPercent(value: number): string {
  return String(Math.round(value * 10_000) / 100);
}

/** A downward-rounded percentage suitable for an asset-height container unit. */
function containmentPercentage(value: number): string {
  return String(Math.floor(value * 100_000_000) / 1_000_000);
}
